//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication.Models
{ 
    public partial class Hrana
    {
        public int id { get; set; }
        public string vrsta_obroka { get; set; }
        public string naziv_proizvoda { get; set; }
        public double tezina { get; set; }
        public double kalorije { get; set; }
        public double suma_kalorija { get; set; }
    }
}
